version: "3.9"

services:

  # TODO: Add healthcheck
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env

  # TODO: Add depends_on
  openai_telegram_bot:
    build: .
    env_file:
      - .env
